spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:sewon@221}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/sewon_ams
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:true}
        show_sql: ${SHOW_SQL:true}
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
    open-in-view: false


  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:admin}
    password: ${RABBITMQ_PASS:admin123}
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration


caffeine:
  maximum-size: ${CAFFEINE_MAX_SIZE:10000}
  expiration-minute: ${CAFFEINE_MINUTE:30}
  expiration-day: ${CAFFEINE_DAY:3}



  # 개발 때 사용
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace


