-- This file is used to initialize the database schema and data for the application.
create table account
(
    id             bigint generated by default as identity,
    username       varchar(50)  not null,
    password       varchar(350) not null,
    affiliation_id bigint       not null,
    name           varchar(50)  not null,
    role           smallint,
    created_at     timestamp(6) not null,
    deleted_at     timestamp(6),
    updated_at     timestamp(6),
    primary key (id)
);
create table affiliation
(
    id         bigint generated by default as identity,
    company    varchar(50)  not null,
    department varchar(50)  not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6),
    deleted_at timestamp(6),
    primary key (id)
);
create table asset
(
    id                bigint generated by default as identity,
    division          smallint     not null,
    status            smallint     not null,
    manufacturer      varchar(255) not null,
    model             varchar(255) not null,
    acquisition_price integer      not null,
    acquisition_date  timestamp(6) not null,
    account_id        bigint       not null,
    asset_location_id bigint       not null,
    asset_type_id     bigint       not null,
    d_type            varchar(31)  not null,
    created_at        timestamp(6) not null,
    deleted_at        timestamp(6),
    updated_at        timestamp(6),
    primary key (id)
);
create table asset_inbound
(
    id                bigint generated by default as identity,
    inbounded_type    smallint     not null,
    inbounded_at      timestamp(6) not null,
    account_id        bigint       not null,
    asset_id          bigint       not null,
    asset_location_id bigint       not null,
    created_at        timestamp(6) not null,
    updated_at        timestamp(6),
    deleted_at        timestamp(6),
    primary key (id)
);
create table asset_location
(
    id             bigint generated by default as identity,
    location       varchar(50)  not null,
    affiliation_id bigint       not null,
    created_at     timestamp(6) not null,
    updated_at     timestamp(6),
    deleted_at     timestamp(6),
    primary key (id)
);
create table asset_outbound
(
    id                bigint generated by default as identity,
    outbound_type     smallint     not null,
    outbound_at       timestamp(6) not null,
    account_id        bigint       not null,
    asset_id          bigint       not null,
    asset_location_id bigint       not null,
    created_at        timestamp(6) not null,
    updated_at        timestamp(6),
    deleted_at        timestamp(6),
    primary key (id)
);
create table asset_rental
(
    id                bigint generated by default as identity,
    account_id        bigint       not null,
    asset_id          bigint       not null,
    asset_location_id bigint       not null,
    asset_inbound_id  bigint,
    asset_outbound_id bigint,
    rented_at         timestamp(6) not null,
    returned_at       timestamp(6),
    created_at        timestamp(6) not null,
    updated_at        timestamp(6),
    deleted_at        timestamp(6),
    primary key (id)
);
create table asset_type
(
    id            bigint generated by default as identity,
    name          varchar(50)  not null,
    asset_type_id bigint,
    created_at    timestamp(6) not null,
    updated_at    timestamp(6),
    deleted_at    timestamp(6),
    primary key (id)
);
create table barcode
(
    id         bigint generated by default as identity,
    value      varchar(255) not null unique,
    asset_id   bigint       not null unique,
    created_at timestamp(6) not null,
    updated_at timestamp(6),
    deleted_at timestamp(6),
    primary key (id)
);
create table electronic_asset
(
    id      bigint      not null,
    cpu     varchar(50) not null,
    ram     SMALLINT    not null,
    storage numeric(6, 3),
    gpu     varchar(50),
    primary key (id)
);
create table notification
(
    id              bigint generated by default as identity,
    content         varchar(300) not null,
    notification_at timestamp(6) not null,
    is_read         smallint     not null,
    account_id      bigint       not null,
    created_at      timestamp(6) not null,
    updated_at      timestamp(6),
    deleted_at      timestamp(6),
    primary key (id)
);
create table asset_stocking_taking
(
    id           bigint generated by default as identity,
    auditing_at  timestamp(6) not null,
    completed_at timestamp(6),
    account_id   bigint       not null,
    created_at   timestamp(6) not null,
    updated_at   timestamp(6),
    deleted_at   timestamp(6),
    primary key (id)
);
create table asset_stock_taking_item
(
    id                    bigint generated by default as identity,
    stock_taking_status   smallint     not null,
    checked_at            timestamp(6) not null,
    checking_status       smallint     not null,
    remark                varchar(300),
    asset_id              bigint       not null,
    asset_stock_taking_id bigint       not null,
    asset_location_id     bigint       not null,
    created_at            timestamp(6) not null,
    updated_at            timestamp(6),
    deleted_at            timestamp(6),
    primary key (id)
);


-- Add foreign key constraints and indexes
alter table if exists account
    add constraint fk_account_affiliation_id_affiliation
        foreign key (affiliation_id)
            references affiliation;
create index idx_account_affiliation_id
    on account (affiliation_id);


alter table if exists asset
    add constraint fk_asset_account_id_account
        foreign key (account_id)
            references account;
create index idx_asset_account_id
    on asset (account_id);


alter table if exists asset
    add constraint fk_asset_asset_location_id_asset_location
        foreign key (asset_location_id)
            references asset_location;
create index idx_asset_asset_location_id
    on asset (asset_location_id);


alter table if exists asset
    add constraint fk_asset_asset_type_id_asset_type
        foreign key (asset_type_id)
            references asset_type;
create index idx_asset_asset_type_id
    on asset (asset_type_id);


alter table if exists asset_inbound
    add constraint fk_asset_inbound_account_id_account
        foreign key (account_id)
            references account;
create index idx_asset_inbound_account_id
    on asset_inbound (account_id);


alter table if exists asset_inbound
    add constraint fk_asset_inbound_asset_id_asset
        foreign key (asset_id)
            references asset;
create index idx_asset_inbound_asset_id
    on asset_inbound (asset_id);


alter table if exists asset_inbound
    add constraint fk_asset_inbound_asset_location_id_asset_location
        foreign key (asset_location_id)
            references asset_location;
create index idx_asset_inbound_asset_location_id
    on asset_inbound (asset_location_id);


alter table if exists asset_location
    add constraint fk_asset_location_affiliation_id_affiliation
        foreign key (affiliation_id)
            references affiliation;
create index idx_asset_location_affiliation_id
    on asset_location (affiliation_id);


alter table if exists asset_outbound
    add constraint fk_asset_outbound_account_id_account
        foreign key (account_id)
            references account;
create index idx_asset_outbound_account_id
    on asset_outbound (account_id);


alter table if exists asset_outbound
    add constraint fk_asset_outbound_asset_id_asset
        foreign key (asset_id)
            references asset;
create index idx_asset_outbound_asset_id
    on asset_outbound (asset_id);


alter table if exists asset_outbound
    add constraint fk_asset_outbound_asset_location_id_asset_location
        foreign key (asset_location_id)
            references asset_location;
create index idx_asset_outbound_asset_location_id
    on asset_outbound (asset_location_id);


alter table if exists asset_rental
    add constraint fk_asset_rental_account_id_account
        foreign key (account_id)
            references account;
create index idx_asset_rental_account_id
    on asset_rental (account_id);


alter table if exists asset_rental
    add constraint fk_asset_rental_asset_id_asset
        foreign key (asset_id)
            references asset;
create index idx_asset_rental_asset_id
    on asset_rental (asset_id);


alter table if exists asset_rental
    add constraint asset_rental_asset_inbound_id_asset_inbound
        foreign key (asset_inbound_id)
            references asset_inbound;
create index idx_asset_rental_asset_inbound_id
    on asset_rental (asset_inbound_id);


alter table if exists asset_rental
    add constraint fk_asset_rental_asset_location_id_asset_location
        foreign key (asset_location_id)
            references asset_location;
create index idx_asset_rental_asset_location_id
    on asset_rental (asset_location_id);


alter table if exists asset_rental
    add constraint fk_asset_rental_asset_outbound_id_asset_outbound
        foreign key (asset_outbound_id)
            references asset_outbound;
create index idx_asset_rental_asset_outbound_id
    on asset_rental (asset_outbound_id);


alter table if exists asset_type
    add constraint fk_asset_type_asset_type_id_asset_type
        foreign key (asset_type_id)
            references asset_type;
create index idx_asset_type_asset_type_id
    on asset_type (asset_type_id);


alter table if exists barcode
    add constraint fk_barcode_asset_id_asset
        foreign key (asset_id)
            references asset;
create index idx_barcode_asset_id
    on barcode (asset_id);


alter table if exists electronic_asset
    add constraint fk_electronic_asset_id_asset
        foreign key (id)
            references asset;
create index idx_electronic_asset_id
    on electronic_asset (id);


alter table if exists notification
    add constraint fk_notification_account_id_account
        foreign key (account_id)
            references account;
create index idx_notification_account_id
    on notification (account_id);


alter table if exists asset_stocking_taking
    add constraint fk_asset_stock_taking_account_id_account
        foreign key (account_id)
            references account;
create index idx_asset_stock_taking_account_id
    on asset_stocking_taking (account_id);

alter table if exists asset_stock_taking_item
    add constraint fk_asset_stock_taking_item_asset_id_asset
        foreign key (asset_id) references asset;

alter table if exists asset_stock_taking_item
    add constraint fk_asset_stock_taking_item_taking_id_asset_stocking_taking
        foreign key (asset_stock_taking_id) references asset_stocking_taking;

alter table if exists asset_stock_taking_item
    add constraint fk_asset_stock_taking_item_asset_location_id_asset_location
        foreign key (asset_location_id) references asset_location;

alter table if exists asset_stock_taking_item
    add constraint uk_asset_id_asset_stock_taking_id
        unique (asset_id, asset_stock_taking_id);
