-- This file is used to initialize the database schema and data for the application.
create table account
(
    id             bigint generated by default as identity,
    username       varchar(50)  not null,
    password       varchar(350) not null,
    affiliation_id bigint       not null,
    name           varchar(50)  not null,
    role           smallint,
    created_at     timestamp(6) not null,
    deleted_at     timestamp(6),
    updated_at     timestamp(6),
    primary key (id)
);
create table affiliation
(
    id             bigint generated by default as identity,
    corporation_id bigint       not null,
    department     varchar(50)  not null,
    created_at     timestamp(6) not null,
    updated_at     timestamp(6),
    deleted_at     timestamp(6),
    primary key (id)
);

create table corporation
(
    id          bigint generated by default as identity,
    name        varchar(10)  not null,
    nation_type smallint     not null,
    created_at  timestamp(6) not null,
    updated_at  timestamp(6),
    deleted_at  timestamp(6),
    primary key (id)
);

create table asset
(
    id                bigint generated by default as identity,
    division          smallint     not null,
    status            smallint     not null,
    manufacturer      varchar(255) not null,
    model             varchar(255) not null,
    acquisition_price integer      not null,
    acquisition_date  timestamp(6) not null,
    account_id        bigint       not null,
    asset_location_id bigint       not null,
    asset_type_id     bigint       not null,
    d_type            varchar(31)  not null,
    created_at        timestamp(6) not null,
    deleted_at        timestamp(6),
    updated_at        timestamp(6),
    primary key (id)
);
create table asset_inbound
(
    id                bigint generated by default as identity,
    inbounded_type    smallint     not null,
    inbounded_at      timestamp(6) not null,
    account_id        bigint       not null,
    asset_id          bigint       not null,
    asset_location_id bigint       not null,
    created_at        timestamp(6) not null,
    updated_at        timestamp(6),
    deleted_at        timestamp(6),
    primary key (id)
);
create table asset_location
(
    id             bigint generated by default as identity,
    location       varchar(50)  not null,
    affiliation_id bigint       not null,
    created_at     timestamp(6) not null,
    updated_at     timestamp(6),
    deleted_at     timestamp(6),
    primary key (id)
);
create table asset_outbound
(
    id                bigint generated by default as identity,
    outbound_type     smallint     not null,
    outbound_at       timestamp(6) not null,
    account_id        bigint       not null,
    asset_id          bigint       not null,
    asset_location_id bigint       not null,
    created_at        timestamp(6) not null,
    updated_at        timestamp(6),
    deleted_at        timestamp(6),
    primary key (id)
);
create table asset_rental
(
    id                bigint generated by default as identity,
    account_id        bigint       not null,
    asset_id          bigint       not null,
    asset_location_id bigint       not null,
    asset_inbound_id  bigint,
    asset_outbound_id bigint,
    status            smallint     not null,
    rented_at         date         not null,
    from_at           date         not null,
    to_at             date         not null,
    returned_at       date,
    created_at        timestamp(6) not null,
    updated_at        timestamp(6),
    deleted_at        timestamp(6),
    primary key (id)
);
create table asset_type
(
    id            bigint generated by default as identity,
    name          varchar(50)  not null,
    asset_type_id bigint,
    nation_type   smallint     not null,
    created_at    timestamp(6) not null,
    updated_at    timestamp(6),
    deleted_at    timestamp(6),
    primary key (id)
);
create table barcode
(
    id         bigint generated by default as identity,
    value      varchar(255) not null,
    asset_id   bigint       not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6),
    deleted_at timestamp(6),
    primary key (id)
);
create table electronic_asset
(
    id      bigint      not null,
    cpu     varchar(50) not null,
    ram     SMALLINT    not null,
    storage numeric(7, 3),
    gpu     varchar(50),
    primary key (id)
);
create table notification
(
    id              bigint generated by default as identity,
    content         varchar(300) not null,
    notification_at timestamp(6) not null,
    is_read         smallint     not null,
    account_id      bigint       not null,
    created_at      timestamp(6) not null,
    updated_at      timestamp(6),
    deleted_at      timestamp(6),
    primary key (id)
);
create table asset_stock_taking
(
    id                bigint generated by default as identity,
    auditing_at       date         not null,
    account_id        bigint       not null,
    asset_location_id bigint       not null,
    created_at        timestamp(6) not null,
    updated_at        timestamp(6),
    deleted_at        timestamp(6),
    primary key (id)
);
create table asset_stock_taking_item
(
    id                    bigint generated by default as identity,
    checking_status       smallint     not null,
    asset_id              bigint       not null,
    asset_stock_taking_id bigint       not null,
    asset_location_id     bigint       not null,
    is_changed            smallint,
    created_at            timestamp(6) not null,
    updated_at            timestamp(6),
    deleted_at            timestamp(6),
    primary key (id)
);

-- Account
-- Add foreign key constraints
alter table if exists account
    add constraint fk_account_affiliation_id_affiliation
        foreign key (affiliation_id)
            references affiliation;
-- Add indexes
create index idx_account_affiliation_id
    on account (affiliation_id) where deleted_at is null;
create index idx_account_username
    on account (username) where deleted_at is null;


-- Affiliation
-- Add foreign key constraints
alter table if exists affiliation
    add constraint fk_affiliation_corporation_id_corporation
        foreign key (corporation_id) references corporation;
-- Add indexes
create index idx_affiliation_corporation_id
    on affiliation (corporation_id) where deleted_at is null;
create index idx_affiliation_department
    on affiliation (department) where deleted_at is null;


-- Corporation
-- Add indexes
create index idx_corporation_name
    on corporation (name) where deleted_at is null;


-- Asset
-- Add foreign key constraints
alter table if exists asset
    add constraint fk_asset_account_id_account
        foreign key (account_id)
            references account;
alter table if exists asset
    add constraint fk_asset_asset_location_id_asset_location
        foreign key (asset_location_id)
            references asset_location;
alter table if exists asset
    add constraint fk_asset_asset_type_id_asset_type
        foreign key (asset_type_id)
            references asset_type;
alter table if exists electronic_asset
    add constraint fk_electronic_asset_id_asset
        foreign key (id)
            references asset;
-- Add indexes
create index idx_asset_account_id
    on asset (account_id) where deleted_at is null;
create index idx_asset_asset_location_id
    on asset (asset_location_id) where deleted_at is null;
create index idx_asset_asset_type_id
    on asset (asset_type_id) where deleted_at is null;
create index idx_electronic_asset_id
    on electronic_asset (id);
create index idx_asset_d_type
    on asset (d_type) where deleted_at is null;


-- Asset Inbound
-- Add foreign key constraints
alter table if exists asset_inbound
    add constraint fk_asset_inbound_account_id_account
        foreign key (account_id)
            references account;
alter table if exists asset_inbound
    add constraint fk_asset_inbound_asset_id_asset
        foreign key (asset_id)
            references asset;
alter table if exists asset_inbound
    add constraint fk_asset_inbound_asset_location_id_asset_location
        foreign key (asset_location_id)
            references asset_location;
-- Add indexes
create index idx_asset_inbound_account_id
    on asset_inbound (account_id) where deleted_at is null;
create index idx_asset_inbound_asset_id
    on asset_inbound (asset_id) where deleted_at is null;
create index idx_asset_inbound_asset_location_id
    on asset_inbound (asset_location_id) where deleted_at is null;


-- AssetLocation
-- Add foreign key constraints
alter table if exists asset_location
    add constraint fk_asset_location_affiliation_id_affiliation
        foreign key (affiliation_id)
            references affiliation;
-- Add indexes
create index idx_asset_location_affiliation_id
    on asset_location (affiliation_id) where deleted_at is null;


-- AssetOutbound
-- Add foreign key constraints
alter table if exists asset_outbound
    add constraint fk_asset_outbound_account_id_account
        foreign key (account_id)
            references account;
alter table if exists asset_outbound
    add constraint fk_asset_outbound_asset_id_asset
        foreign key (asset_id)
            references asset;
alter table if exists asset_outbound
    add constraint fk_asset_outbound_asset_location_id_asset_location
        foreign key (asset_location_id)
            references asset_location;
-- Add indexes
create index idx_asset_outbound_account_id
    on asset_outbound (account_id) where deleted_at is null;
create index idx_asset_outbound_asset_id
    on asset_outbound (asset_id) where deleted_at is null;
create index idx_asset_outbound_asset_location_id
    on asset_outbound (asset_location_id) where deleted_at is null;


-- AssetRental
-- Add foreign key constraints
alter table if exists asset_rental
    add constraint fk_asset_rental_account_id_account
        foreign key (account_id)
            references account;
alter table if exists asset_rental
    add constraint fk_asset_rental_asset_id_asset
        foreign key (asset_id)
            references asset;
alter table if exists asset_rental
    add constraint asset_rental_asset_inbound_id_asset_inbound
        foreign key (asset_inbound_id)
            references asset_inbound;
alter table if exists asset_rental
    add constraint fk_asset_rental_asset_location_id_asset_location
        foreign key (asset_location_id)
            references asset_location;
alter table if exists asset_rental
    add constraint fk_asset_rental_asset_outbound_id_asset_outbound
        foreign key (asset_outbound_id)
            references asset_outbound;
-- Add indexes
create index idx_asset_rental_account_id
    on asset_rental (account_id) where deleted_at is null;
create index idx_asset_rental_asset_id
    on asset_rental (asset_id) where deleted_at is null;
create index idx_asset_rental_asset_inbound_id
    on asset_rental (asset_inbound_id) where deleted_at is null;
create index idx_asset_rental_asset_location_id
    on asset_rental (asset_location_id) where deleted_at is null;
create index idx_asset_rental_asset_outbound_id
    on asset_rental (asset_outbound_id) where deleted_at is null;


-- AssetType
-- Add foreign key constraints
alter table if exists asset_type
    add constraint fk_asset_type_asset_type_id_asset_type
        foreign key (asset_type_id)
            references asset_type;
-- Add indexes
create index idx_asset_type_asset_type_id
    on asset_type (asset_type_id) where deleted_at is null;
create index idx_asset_type_name
    on asset_type (name) where deleted_at is null;


-- Barcode
-- Add foreign key constraints
alter table if exists barcode
    add constraint fk_barcode_asset_id_asset
        foreign key (asset_id)
            references asset;
-- Add unique key constraints
alter table if exists barcode
    add constraint barcode_asset_id
        unique (asset_id);
alter table if exists barcode
    add constraint barcode_value
        unique (value);


-- Notification
-- Add foreign key constraints
alter table if exists notification
    add constraint fk_notification_account_id_account
        foreign key (account_id)
            references account;
-- Add indexes
create index idx_notification_account_id
    on notification (account_id) where deleted_at is null;


-- AssetStockTaking
-- Add foreign key constraints
alter table if exists asset_stock_taking
    add constraint fk_asset_stock_taking_account_id_account
        foreign key (account_id)
            references account;
alter table if exists asset_stock_taking
    add constraint fk_asset_stock_taking_location_id_asset_location
        foreign key (asset_location_id)
            references asset_location;
-- Add unique key constraints
alter table if exists asset_stock_taking
    add constraint uq_location_id_auditing_at
        unique (asset_location_id, auditing_at);
-- Add indexes
create index idx_asset_stock_taking_account_id
    on asset_stock_taking (account_id) where deleted_at is null;


-- AssetStockTakingItem
-- Add foreign key constraints
alter table if exists asset_stock_taking_item
    add constraint fk_asset_stock_taking_item_asset_id_asset
        foreign key (asset_id) references asset;
alter table if exists asset_stock_taking_item
    add constraint fk_asset_stock_taking_item_taking_id_asset_stock_taking
        foreign key (asset_stock_taking_id) references asset_stock_taking;
alter table if exists asset_stock_taking_item
    add constraint fk_asset_stock_taking_item_asset_location_id_asset_location
        foreign key (asset_location_id) references asset_location;
-- Add unique key constraints
alter table if exists asset_stock_taking_item
    add constraint uk_asset_id_asset_stock_taking_id
        unique (asset_id, asset_stock_taking_id);
