server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true
  tomcat:
    threads:
      max: 200
      min-spare: 10
    max-connections: 10000
    accept-count: 100
    connection-timeout: 20000
    keep-alive-timeout: 20000

  port: 8888

spring:
  config:
    import: application.yml, application-infra.yml

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  prometheus:
    metrics:
      export:
        enabled: true


jwt:
  secret: ${JWT_SECRET:JWSEREWSEWQEASDASDADWASDADASS32SS112355WASDASADAKBDLTMWSD}
  access-token-expiration: ${JWT_ACCESS_EXPIRE:900000}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRE:1800000}
