services:
  postgres:
    container_name: ams-postgres
    image: postgres:14.4
    ports:
      - "5432:5432"

    restart: on-failure

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sewon@221
      - POSTGRES_DB=sewon_ams

    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

    expose:
      - 5432

volumes:
  pgdata: